# Generated by Django 4.0.6 on 2022-09-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costcentr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('emply', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=225)),
                ('group_alias', models.CharField(max_length=225, null=True)),
                ('group_under', models.CharField(max_length=225)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.BooleanField(default=False)),
                ('debit_credit', models.BooleanField(default=False)),
                ('calculation', models.BooleanField(default=False)),
                ('invoice', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_alias', models.CharField(max_length=255)),
                ('group_under', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.CharField(max_length=255)),
                ('debit_credit', models.CharField(max_length=255)),
                ('calculation', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally2_app.companies')),
            ],
        ),
    ]
