# Generated by Django 4.0.6 on 2022-09-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0002_create_attendence_create_employeegroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
