# Generated by Django 4.0.6 on 2022-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0003_createstockgrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costcentr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('emply', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='cost_centre',
            name='company',
        ),
        migrations.DeleteModel(
            name='CreateStockGrp',
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
        migrations.RemoveField(
            model_name='tally_group',
            name='company',
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='cost_centre',
        ),
        migrations.DeleteModel(
            name='tally_group',
        ),
    ]
