# Generated by Django 4.0.6 on 2022-09-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0004_costcentr_remove_cost_centre_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Null', max_length=225)),
                ('alias', models.CharField(blank=True, default='Null', max_length=225)),
                ('under', models.CharField(blank=True, default='Null', max_length=225)),
                ('nature_of_group', models.CharField(blank=True, default='Null', max_length=225)),
                ('does_it_affect', models.CharField(blank=True, default='Null', max_length=225)),
                ('gp_behaves_like_sub_ledger', models.CharField(blank=True, default='Null', max_length=225)),
                ('nett_debit_credit_bal_reporting', models.CharField(blank=True, default='Null', max_length=225)),
                ('used_for_calculation', models.CharField(blank=True, default='Null', max_length=225)),
                ('method_to_allocate_usd_purchase', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='GrpAlter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('nature', models.CharField(max_length=225)),
                ('grp', models.CharField(max_length=225)),
                ('nett', models.CharField(max_length=225)),
                ('used', models.CharField(max_length=225)),
                ('method', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='grunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('und', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_alias', models.CharField(max_length=255)),
                ('group_under', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.CharField(max_length=255)),
                ('debit_credit', models.CharField(max_length=255)),
                ('calculation', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally2_app.companies')),
            ],
        ),
    ]
