# Generated by Django 4.0.6 on 2022-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0007_lbank_lcheque_ledger_maingroup_print_cheque_subgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costcentr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('emply', models.CharField(max_length=225)),
            ],
        ),
    ]
