# Generated by Django 4.0.6 on 2022-09-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0008_costcentr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maingroup',
            old_name='affect_gp',
            new_name='nature',
        ),
        migrations.RemoveField(
            model_name='maingroup',
            name='under_group',
        ),
    ]
