# Generated by Django 4.0.6 on 2022-09-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0009_rename_affect_gp_maingroup_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingroup',
            name='affect_gp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
