# Generated by Django 4.0.6 on 2022-09-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally2_app', '0010_maingroup_affect_gp'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally2_app.maingroup')),
                ('S_count', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tally2_app.subgroup')),
            ],
        ),
    ]
